修复当本地歌词找不到中括号时崩溃的问题
Ferry-200/coriander_player pull request #104
Opened 2024-08-28 17:49 UTC by Zhoucheng133

还有一个部署遇到的问题：在`pubspec.yaml`中最好修改一下：
```yaml
# - flutter_rust_bridge: ^2.0.0
# 去除^
- flutter_rust_bridge: 2.0.0
```
不然新获取的版本不符合会报错

2024-08-28 17:56 UTC, Zhoucheng133 commented
打开会黑屏一下，因为用的window_manager依赖，可以根据[这个链接](https://pub.dev/packages/window_manager)的Hidden at launch方法去除开屏的黑块

2024-08-28 18:13 UTC, Ferry-200 commented
谢谢 pr。看起来没什么问题，可以马上合并。

另外 issue 是误操作连接上了吗？我不认为这个 pr 与 #79 相关。

pubspec 那个文件都是 flutter pub add 的时候修改的，我完全没注意过这个问题。后面我再看看。

2024-08-28 18:26 UTC, Zhoucheng133 commented
和关联的那个无关
打#没注意链接上了:(

2024-08-28 18:26 UTC, Ferry-200 requested changes

2024-08-28 18:26 UTC, Ferry-200 commented on lib/lyric/lrc.dart
> +    }
下面的 indexOf 会在找不到时返回 -1，所以可以不使用 contains 而直接判断 indexOf 的结果是否为 -1。如果是就返回 null，不是就继续进行。

2024-08-28 18:27 UTC, Ferry-200 commented
感觉 contains 是不必要的，按照审查要求改一下就好🤔。

2024-08-28 18:30 UTC, Zhoucheng133 commented
不对，使用原来的：
```dart
var lrcTimeString = line.substring(
  line.indexOf("[") + 1,
  line.indexOf("]"),
)
```
如果没有]，那么后面那个是-1，substring不能用负数作为参数，而且必须大于等于line.indexOf("[") + 1

2024-08-28 18:34 UTC, Ferry-200 commented
> 不对，使用原来的：
> ```dart
> var lrcTimeString = line.substring(
>   line.indexOf("[") + 1,
>   line.indexOf("]"),
> )
> ```
> 如果没有]，那么后面那个是-1，substring不能用负数作为参数，而且必须大于等于line.indexOf("[") + 1

这样该就好

```dart
final left = line.indexOf("[");
final right = line.indexOf("]");
if (left == -1 || right == -1) return null;
var lrcTimeString = line.substring(
   left + 1,
   right
 );
```

2024-08-28 18:36 UTC, Zhoucheng133 commented
这样也可以吧:D
另外把fromLrcText返回值改为Lrc?来返回null以通过其它方式获取歌词

2024-08-28 18:46 UTC, Ferry-200 commented
> 这样也可以吧:D
> 另外把fromLrcText返回值改为Lrc?来返回null以通过其它方式获取歌词

这个先不改吧，麻烦先去掉 ?。
https://github.com/Ferry-200/coriander_player/blob/main/lib%2Flyric%2Flrc.dart#L161-L161
引用了该方法，然后我还不确定是否要这样子合并网络歌词的翻译。所以先放着。

2024-08-28 18:49 UTC, Ferry-200 commented
> 这样也可以吧:D
> 另外把fromLrcText返回值改为Lrc?来返回null以通过其它方式获取歌词

这个可以。另外通过其他方式获取歌词是指什么

2024-08-28 19:06 UTC, Zhoucheng133 commented
fromLrcText这个不加`?`怎么返回null哇
你在[lyric_service中](https://github.com/Ferry-200/coriander_player/blob/60846d95bac072c03d66d24312cceb1d9d0d6806/lib/play_service/lyric_service.dart#L93)在调用`Lrc.fromAudioPath(nowPlaying)`的时候，若返回值为null，在本地歌词优先的情况下会从`getMostMatchedLyric`这个方法中获取歌词（应该是在线歌词？），如果`getMostMatchedLyric(nowPlaying)`和`Lrc.fromAudioPath(nowPlaying)`都为null，那么`lyricNullable`在[vertical_lyric_view](https://github.com/Ferry-200/coriander_player/blob/60846d95bac072c03d66d24312cceb1d9d0d6806/lib/page/now_playing_page/component/vertical_lyric_view.dart#L59)里为空（也就是都没有获取到歌词），根据[下面的判定](https://github.com/Ferry-200/coriander_player/blob/60846d95bac072c03d66d24312cceb1d9d0d6806/lib/page/now_playing_page/component/vertical_lyric_view.dart#L76)则显示无歌词界面

```dart
if(本地歌词优先){
  if(本地歌词结果为空){
    if(网络歌词结果为空){
      显示无歌词
    }else{
      显示网络歌词
    }
  }else{
     显示本地歌词
  }
}else{
  上面顺序反过来
}
```

2024-08-28 19:09 UTC, Zhoucheng133 commented
`fromAudioPath`这个方法本来就是`Lrc?`，你把内层的`Lrc.fromLrcText`也改成`Lrc?`不影响结果，只是没有匹配到`[]`的时候会返回null罢了  
顺便一提调用`fromLrcText`没怎么看懂为啥类的内部为啥要`<类名>.<方法名>`，直接`<方法名>`就可以了

2024-08-28 19:15 UTC, Ferry-200 commented
是这种意思🧐没问题。另外多写类名应该是我顺手写了。先不改吧（

2024-09-02 15:04 UTC, merged

2024-09-02 17:48 UTC, Ferry-200 approved these changes