feat(UI): 使上下句样式与其他歌词一致&增加不透明度
Ferry-200/coriander_player pull request #82
Opened 2024-08-11 17:54 UTC by shing-yu

同时增加非当前句歌词的不透明度至18%
close #66.

预览：
![image](https://github.com/user-attachments/assets/c4e758d7-75c0-4231-b67f-afcda8788e3d)

2024-08-11 22:15 UTC, Ferry-200 requested changes

2024-08-11 22:15 UTC, Ferry-200 commented on lib/page/now_playing_page/component/vertical_lyric_view.dart
>          if (mainLine >= 2 && i <= mainLine - 2) {
可以减少 if 数量。这里把两个 2 都改成 1。

2024-08-11 22:15 UTC, Ferry-200 commented on lib/page/now_playing_page/component/vertical_lyric_view.dart
>          if (mainLine >= 1 && i == mainLine - 1) {
这个 if 分支可以完全删掉

2024-08-11 22:15 UTC, Ferry-200 commented on lib/page/now_playing_page/component/vertical_lyric_view.dart
>          if (mainLine < widget.lyric.lines.length - 1 && i == mainLine + 1) {
这个 if 分支也可以完全删掉。

2024-08-11 22:15 UTC, Ferry-200 commented on lib/page/now_playing_page/component/vertical_lyric_view.dart
>          if (mainLine < widget.lyric.lines.length - 2 && i >= mainLine + 2) {
同样是把两个都 2 改成 1

2024-08-11 22:17 UTC, Ferry-200 commented
提了一些建议。
应该是这一段古老代码写得太乱了所以你没看懂具体是什么意思😂

2024-08-12 08:10 UTC, shing-yu commented
啊，好的，我改下

2024-08-12 11:59 UTC, shing-yu commented
改好了（

2024-08-12 12:04 UTC, Ferry-200 commented
怎么写的更加乱了😂

也行吧。

2024-08-12 12:05 UTC, shing-yu commented
啊？只是把剩下的两个if也合成一个了（

2024-08-12 12:05 UTC, merged

2024-09-02 17:49 UTC, Ferry-200 approved these changes